package com.mindolph.mindmap.constant;

/**
 * @author mindolph.com@gmail.com
 */
public interface VendorConstants {

    String GENERATE_BY = "Generated by Mindolph (https://github.com/mindolph/Mindolph)";
}
