package com.mindolph.base.constant;

/**
 * @author mindolph.com@gmail.com
 * @see com.mindolph.base.FontIconManager
 */
public enum IconKey {
    PLUS, OPEN, SAVE, REDO, UNDO, CLEAR, FOLD, UNFOLD, GEAR, FILE, FONT,
    BROWSE, LOCK, SELECT, UNSELECT, REFRESH, SEARCH, REPLACE, SORT,
    YES, NO, OK, CANCEL, CLOSE, EXIT, FINISH,
    TOPIC,
    CODE, PREVIEW, SWITCH_HORIZONTAL, SWITCH_VERTICAL, SYSTEM,
    RENAME, CLONE, DELETE, COLLAPSE_ALL, EXPAND_ALL, COLLAPSE_FOLDERS,
    ALIGN, ALIGN_LEFT, ALIGN_RIGHT, ALIGN_CENTER,
    COPY, CUT, PASTE, WRAP,
    ADD_CHILD, // deprecated
    EDIT_TEXT, EDIT_COLORS, SHOW_JUMPS, CONVERT,
    NOTE, FILE_LINK, URI, JUMP, EMOTICONS, EXPORT, IMPORT, IMAGE,
    NEXT, PREVIOUS, CASE_SENSITIVITY,
    PRINTER, PAGE,
    WORKSPACE, RECENT_LIST, WORKSPACE_TREE,
    FOLDER, PDF, FILE_MMD, FILE_MD, FILE_CSV, FILE_PUML, FILE_IMG, FILE_TXT, UNKNOWN_FILE,
    BOLD, ITALIC, INDENT_DECREASE, INDENT_INCREASE, BULLET_LIST, NUMBER_LIST, QUOTE, TABLE, CODE_TAG, SEPARATOR,
    H1, H2, H3, H4, H5, H6
}
