package com.mindolph.base.constant;

/**
 * @author mindolph.com@gmail.com
 * @see com.mindolph.base.FontIconManager
 */
public enum IconKey {
    OPEN, SAVE, REDO, UNDO, CLEAR, FOLD, UNFOLD,
    BROWSE, LOCK, SELECT, UNSELECT, REFRESH, SEARCH, REPLACE, SORT,
    YES, NO, OK, CANCEL, CLOSE, EXIT, FINISH,
    TOPIC,
    CODE, PREVIEW, SWITCH_HORIZONTAL, SWITCH_VERTICAL, SYSTEM,
    RENAME, CLONE, DELETE, COLLAPSE_ALL, EXPAND_ALL,
    ALIGN, ALIGN_LEFT, ALIGN_RIGHT, ALIGN_CENTER,
    EDIT_TEXT, ADD_CHILD, EDIT_COLORS, SHOW_JUMPS, CONVERT,
    NOTE, FILE_LINK, URI, JUMP, EMOTICONS, EXPORT, IMPORT, IMAGE,
    NEXT, PREVIOUS, CASE_SENSITIVITY,
    PRINTER, PAGE,
    PDF
}
